import React, { useEffect } from "react";

import styled from "styled-components";
import { useDispatch } from "react-redux";

import Icon from "../shared/Icon";
import { clearPost } from "../../redux/slices/post";
import { setUser, logout } from "../../redux/slices/user";
import { useRouter } from "next/router";
import Link from "next/link";
import Head from "next/head";
import { setHeader } from "../../adapters/xhr";
import { decodeToken } from "../../utils/token-helper";
import { RouteGuard } from "../RouteGuard";

const Wrper = styled.div`
  .header {
    display: flex;
    width: 200px;
    align-items: center;
    justify-content: space-between;
    flex-wrap: nowrap;
    padding: 0.5rem 1rem 0 1rem;
    font-size: 1rem;
  }
  .header i {
    padding: 0.5rem;
  }
  .navigation {
    background-color: ${({ theme }) => theme.primary};
    height: 100vh;
    width: 200px;
    transition: width 0.5s ease;
    overflow-x: hidden;
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    z-index: 2;
    display: flex;
    flex-direction: column;
  }
  .admin-menu {
    list-style: none;
    display: flex;
    flex-direction: column;
    flex: 1;
    margin-bottom: 0;
    padding: 0;
  }
  .menu-item {
    display: flex;
    align-items: center;
    width: 200px;
    color: #5c7080;
    margin: 0.6rem 0;
    transition: color 0.6s ease, background-color 0.3s ease, border 0.6s ease;
  }
  .menu-item:hover:not(.active) a .icon {
    color: ${({ theme }) => theme.accent};
    transition: color 0.3s ease;
  }
  .menu-item:hover:not(.active) a span::after {
    background-color: ${({ theme }) => theme.accent};
    width: 100%;
  }
  .menu-item.active {
    color: ${({ theme }) => theme.text};
    border-right: 3px solid ${({ theme }) => theme.accent};
  }
  .menu-item a {
    text-decoration: none;
    color: inherit;
    width: 100%;
    flex: 1;
    padding: 0.5rem 1rem;
  }
  .menu-item a span {
    position: relative;
  }
  .menu-item a span::after {
    content: "";
    display: block;
    position: absolute;
    left: 0;
    right: 0;
    bottom: 0;
    height: 1px;
    width: 0;
    background-color: transparent;
    transition: all 0.3s ease;
  }
  .menu-item .icon {
    margin-left: 1rem;
  }
  .main-section {
    display: flex;
    justify-content: center;
    align-items: center;
    margin-right: 200px;
  }
  .back-icon {
    color: ${({ theme }) => theme.text};
  }
  .logo {
    transition: all 50ms ease-in-out;
    display: block;
    background: url("/logo.svg") no-repeat center center;
    background-size: contain;
    width: 50px;
    height: 39px;
    line-height: 0;
    font-size: 0;
    color: transparent;
  }
  @media (max-width: 500px) {
    .navigation {
      width: 56px;
    }
    .navigation:hover {
      width: 200px;
    }
    .main-section {
      margin-right: 56px;
    }
    .header {
      padding-right: 0.3rem;
    }
  }
`;

const DashboardLayout = ({ children }) => {
  const router = useRouter();
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(clearPost());
    try {
      const token = localStorage.getItem("token");
      if (token) {
        setHeader(token);
        const decodedToken = decodeToken(token);
        if (decodedToken) {
          dispatch(setUser(decodedToken.user));
        } else {
          localStorage.removeItem("token");
          dispatch(logout());
        }
      }
      // dispatch(getPosts());
    } catch (error) {
      console.log(error);
    }
    // eslint-disable-next-line
  }, []);

  return (
    <RouteGuard>
      <Wrper className="dashboard-layout rtl">
        <Head>
          <title>داشبورد</title>
          <meta charset="utf-8" />
          <link rel="icon" href="/logo.svg" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta name="theme-color" content="#000000" />
          <meta name="description" content="Generated by create next app" />
        </Head>
        <nav className="navigation p-0">
          <div className="header">
            <Link href="/">
              <a className="logo p-0">Logo</a>
            </Link>
            <Link href="/" replace>
              <a>
                <Icon className="back-icon" icon="arrow-left" size={24} />
              </a>
            </Link>
          </div>
          <ul className="admin-menu">
            <li
              className={`menu-item ${
                router.pathname === "/dashboard" ? "active" : ""
              }`}
            >
              <Link href="/dashboard">
                <a>
                  <Icon
                    className="icon"
                    icon={`${
                      router.pathname === "/dashboard"
                        ? "profile-filled"
                        : "profile"
                    }`}
                    size={24}
                  />
                  <span>پروفایل</span>
                </a>
              </Link>
            </li>
            <li
              className={`menu-item ${
                router.pathname.includes("/dashboard/work-table")
                  ? "active"
                  : ""
              }`}
            >
              <Link href="/dashboard/work-table">
                <a>
                  <Icon
                    className="icon"
                    icon={`${
                      router.pathname.includes("/dashboard/work-table")
                        ? "create-post-filled"
                        : "create-post"
                    }`}
                    size={24}
                  />
                  <span>میز کار</span>
                </a>
              </Link>
            </li>
            <li
              className={`menu-item ${
                router.pathname === "/dashboard/posts" ? "active" : ""
              }`}
            >
              <Link href="/dashboard/posts">
                <a>
                  <Icon
                    className="icon"
                    icon={`${
                      router.pathname === "/dashboard/posts"
                        ? "posts-filled"
                        : "posts"
                    }`}
                    size={24}
                  />
                  <span>پست ها</span>
                </a>
              </Link>
            </li>
            <li className="menu-item mt-auto">
              <Link href="/logout">
                <a>
                  <Icon className="icon" icon="logout" size={24} />
                  <span>خروج</span>
                </a>
              </Link>
            </li>
          </ul>
        </nav>
        <section className="main-section">{children}</section>
      </Wrper>
    </RouteGuard>
  );
};

export default DashboardLayout;
